server:
  port: 8999
logging:  level:    '[com.example.demo]': debug
#    
#spring:#  thymeleaf:#    prefix: classpath:/templates/
#    suffix: .html
    
management:  endpoints:    web:      exposure:        include:        - '*'